import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TableProvider } from "@init/table";
import { cookies, headers } from "next/headers";
import { Zustand } from "@lib/store";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cooks = await cookies();
  const heads = await headers();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Zustand>
          <TableProvider cookies={cooks.getAll()} headers={heads.entries()}>
            {children}
          </TableProvider>
        </Zustand>
      </body>
    </html>
  );
}
